# Generated by Django 4.2.7 on 2023-11-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='borrow_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
